-- Drop tables
DROP TABLE Resultado;
DROP TABLE Medicamento;
DROP TABLE Enfermedad;
DROP TABLE Paciente;
DROP TABLE Prueba;  

-- Create tables
CREATE TABLE Medicamento (
    idMedicamento            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombreMedicamento        VARCHAR2(100) NOT NULL,
    nombreMedicamentoIngles  VARCHAR2(100) NOT NULL,
    claseMedicamento         VARCHAR2(100) ,
    añoPrimeraMencion        VARCHAR2(30) ,           -- Posible fallo 'ñ'
    instituto                VARCHAR2(100) ,
    estadoActual             VARCHAR2(100) ,
    faseDesarrolloMasAlta    VARCHAR2(50) ,
    suspension               VARCHAR2(200) ,
    mecanismoAcc_patogenoObj VARCHAR2(500) ,
    info                     VARCHAR2(500) ,
    patente                  VARCHAR2(20) 
);

CREATE TABLE Enfermedad (
    idEnfermedad             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombreEnfermedad          VARCHAR2(100) NOT NULL,
    mecanismoResistencia     VARCHAR2(300)
);

CREATE TABLE Paciente (
    idPaciente             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numeroPaciente         NUMBER NOT NULL,
    fechaNac               DATE NOT NULL,
    sexo                   VARCHAR2(20) NOT NULL,
    edad                   NUMBER NOT NULL,
    peso                   NUMBER NOT NULL,
    historiaHClinico       NUMBER ,
    tipoPaciente           VARCHAR2(20) NOT NULL
);

CREATE TABLE Prueba (
    idPrueba              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    servicio              VARCHAR2(20) NOT NULL,
    nomPrueba             VARCHAR2(20) NOT NULL,
    muestra               VARCHAR2(20) NOT NULL,
    muestraNumCultivo     NUMBER NOT NULL
);


CREATE TABLE Resultado (
    idMedicamento            NUMBER,
    idEnfermedad             NUMBER,
    idPaciente               NUMBER,
    idPrueba                 NUMBER,
    sensibilidad             VARCHAR2(20)     NOT NULL,
    PRIMARY KEY (idMedicamento, idEnfermedad, idPaciente, idPrueba),
    FOREIGN KEY (idMedicamento) REFERENCES Medicamento (idMedicamento),
    FOREIGN KEY (idEnfermedad) REFERENCES Enfermedad (idEnfermedad),
    FOREIGN KEY (idPaciente) REFERENCES Paciente (idPaciente),
    FOREIGN KEY (idPrueba) REFERENCES Prueba (idPrueba)
);
